### ISSUE TITLE
关于论文中的Bucket Encoder有些疑问

### ISSUE THREAD

**Issue by cingtiye** [562225807/RoKGDS#2]
您好~
关于您论文中的**Bucket Encoder**，我有几个疑问：
（1）假如有长度在64~128之间的知识M个，这M个是如何输入到Encoder中的，是拼接输入的吗？
（2）不同桶在编码器输出后，是如何得到论文中的**E_K**的？

![image](https://user-images.githubusercontent.com/32251546/173986562-a6e5d454-bd58-40f9-8a81-1e6db746fa52.png)

另外，想咨询一下论文中的解码方式是什么？beam search还是sample？

非常希望能得到您的回复~
祝您阖家欢乐，万事如意~

**Comment by 562225807** [comment]
问题（1）：
假设这M条知识最大长度为128，它们将组成[M,128]的Tensor，然后被输入到Encoder并行编码。
问题（2）：
每个桶中的编码后的知识会会全部拼接在一起组成输出，例如问题1中知识编码后为[M, 128, 768]的输出，其会拼接为[M×128, 768]
问题（3）：
采用的是贪心解码
